COLUMN table_name FORMAT A20
COLUMN rows FORMAT 99999
SELECT 'FACULTY' AS table_name, COUNT(*) AS rows FROM faculty
UNION ALL SELECT 'ADVISOR', COUNT(*) FROM advisor
UNION ALL SELECT 'VENUE_PIC', COUNT(*) FROM venue_pic
UNION ALL SELECT 'SEMESTER', COUNT(*) FROM semester
UNION ALL SELECT 'STUDENT', COUNT(*) FROM student
UNION ALL SELECT 'CLUB', COUNT(*) FROM club
UNION ALL SELECT 'VENUE', COUNT(*) FROM venue
UNION ALL SELECT 'MEMBERSHIP', COUNT(*) FROM membership
UNION ALL SELECT 'CLUB_PRESIDENT', COUNT(*) FROM club_president
UNION ALL SELECT 'EVENT', COUNT(*) FROM event
UNION ALL SELECT 'EVENT_REGISTRATION', COUNT(*) FROM event_registration
ORDER BY table_name;
